### ISSUE TITLE
Current version not showing up in CKAN

### ISSUE THREAD

**Issue by linuxgurugamer** [severedsolo/MADLAD#3]
Not sure why, but this version is not updated in CKAN, following is the error:

Could not find MADLAD entry in zipfile to install

**Comment by DasSkelett** [comment]
> Not sure why

It's what the error says ;)
CKAN searches for a folder matching the identifier by default, which is not present in the latest release: (latest release on top, previous release below)
![grafik](https://user-images.githubusercontent.com/28812678/68073881-05c10100-fd95-11e9-96d9-10132bb06374.png)

We _could_ change the install stanza to get this indexed, but I'd prefer if future releases all follow the structure GameData/MADLAD/<files>. You could do a re-release or re-upload for this version if you want @severedsolo.

**Comment by severedsolo** [comment]
Oh bloody hell, what did I do that for. Sorry. Fixing now.

**Comment by severedsolo** [comment]
Fixed and rereleased

**Comment by linuxgurugamer** [comment]
Happens to all of us.

I hope to be able to start adding the stanza to my parts mods in the next few days
